map_type: costmap

obstacle_range: 3
raytrace_range: 2

transform_tolerance: 1

inflation_radius: 0.4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
